### ISSUE TITLE
No link on gsd5-ticklers

### ISSUE THREAD

**Issue by K0ertis** [roma0104/gsd5-ticklers#7]
Hi! 
The link '$:/plugins/gsd5/ticklers" on http://gsd5.tiddlyspot.com/ under "Other plugins/GSD5 Ticklers" does not contain any links/plugins.

```
Drag-and-drop the following link to your existing GSD5 environment.

$:/plugins/gsd5/ticklers
```

Greetings

**Comment by roma0104** [comment]
Oh thanks for bringing that up.  I forgot to add that plugin into the latest doc updates.  Should be up in the next few hours.

**Comment by roma0104** [comment]
Should be fixed.
